FROM gcr.io/chainpoint-registry/github-chainpoint-chainpoint-services/node-base

COPY node-lib/lib /home/node/app/lib

COPY node-eth-contracts/package.json node-eth-contracts/yarn.lock /home/node/app/
RUN yarn

ADD node-eth-contracts/* /home/node/app/

CMD ["yarn", "migrate"]
